### ISSUE TITLE
The hexagon phenomenom with monsters and your host dang wang

### ISSUE THREAD

**Issue by MetalAze** [DangWang/DangerousAdventures#18]
http://prntscr.com/pxxyn0
http://prntscr.com/pxxz9f
http://prntscr.com/pxxzo7
http://prntscr.com/pxy092

Game has issues with registering and displaying movement properly for monsters other than the first one. You get hexagons left for moves you don't have, sometimes they cover the whole screen and sometimes you have just 2 pieces

also the hexagons stay until it's the turn of the adventurers

**Comment by DangWang** [comment]
Fixed.
