### ISSUE TITLE
Discuss combat

### ISSUE THREAD

**Issue by MetalAze** [DangWang/DangerousAdventures#22]
this is a reminder that we should discuss combat, we should probably wait to discuss until we can get some actual games going and test the combat in motion and get a feel for it, the issue is defense dice are op and we have some options

rework the defense dice (either replacing a block slot with a fail or some other rework for the dice or same thing for the attack dice but a buff like giving true strike to the crit or replacing a fail with a hit)

make the defense dice rare (atm I prefer this because I want defense dice to be useful and decently reliable, so the way you counter it is by overpowering it with more attack dice than they could possibly block or build some other types of attack like magic or pure) 

or a bit of both

**Comment by DangWang** [comment]
This is not an issue with the scripting side of the game. Closing this.
