### ISSUE TITLE
Moving from trap to trap (at least in this build) eats my movement points without actually moving

### ISSUE THREAD

**Issue by MetalAze** [DangWang/DangerousAdventures#7]
Sometimes you can move but a lot of times it simply won't move and it consumes movement points http://prntscr.com/px2x6k

**Comment by MetalAze** [comment]
https://imgur.com/DdWm9j6 here is a gif for demonstration

**Comment by DangWang** [comment]
The trap didn't get triggered. Then the behavior is indeed undefined. The question is why did the trap not get triggered?

**Comment by DangWang** [comment]
Duplicate bug. Traps have a problem in build mode.
